TITLE_LEN = 38

                rsreset
Track_Title     rs.b    TITLE_LEN
Track_Text      rs.b    0

END_TEXT        macro
                dc.b    "                              ",0 ; whitespace before wrap
                even
                endm

;-------------------------------------------------------------------------------
Tracks:
                dc.w    Track_GHIntroduction-TrackData
                dc.w    Track_BayTremoreOldTimes-TrackData
                dc.w    Track_LaamaaSaintLager-TrackData
                dc.w    Track_TobikomiNamkey-TrackData
                dc.w    Track_AlpaandZiphoidAsWeRemain-TrackData
                dc.w    Track_CurtCoolBloatedColonel-TrackData
                dc.w    Track_GeminiDash-TrackData
                dc.w    Track_AndyChypnotized-TrackData
                dc.w    Track_PunnikLies-TrackData
                dc.w    Track_MaakQbix-TrackData
                dc.w    Track_VirgillKeygenX-TrackData
                dc.w    Track_Soda7Appeal-TrackData
                dc.w    Track_TurboKnightRaptureLongtime-TrackData
                dc.w    Track_NotoriousMittenSmitten-TrackData
                dc.w    Track_XYCELeCourant-TrackData
                dc.w    Track_OkeanosTheDawnSkies-TrackData
                dc.w    Track_RobynPurplelily-TrackData
                dc.w    Track_EarthlingTwoTrackWonder-TrackData
                dc.w    Track_TeconEngage-TrackData
                dc.w    Track_NeuroflipFreeCarmela-TrackData
                dc.w    Track_mA2EAuroraNights-TrackData
                dc.w    Track_RaptureSpaceRatatouille-TrackData
                dc.w    Track_OctapusAstroSwong-TrackData
                dc.w    Track_NoolyGoodTimesAreNow-TrackData
                dc.w    Track_YziEnnenolichipitrautaa-TrackData
                dc.w    Track_DvibeHalvTreKaffet-TrackData
                dc.w    Track_Ne7FridayFeelin-TrackData
                dc.w    Track_TriaceUplifter-TrackData
                dc.w    Track_UctumiDisqualified-TrackData
                dc.w    Track_UlrickMachineras-TrackData
                dc.w    Track_NoXSAtChoic3-TrackData
                dc.w    Track_JosssMoonshiner-TrackData
                dc.w    Track_HyperunknowGoatFiction-TrackData
                dc.w    Track_AlexMenchiWelcomeToTheParty-TrackData
                dc.w    Track_GouafhgBrendaandDylan-TrackData
                dc.w    Track_TFXWillows-TrackData
                dc.w    Track_DusthillresidentTetsujin-TrackData
                dc.w    Track_SlashFillingItUp-TrackData
                dc.w    Track_Buddy105Fahrenheit-TrackData
                dc.w    Track_QwanTatsunokoLandscape-TrackData
                dc.w    Track_MaakInMyMemories-TrackData
                dc.w    Track_MrGamerChipex5-TrackData
                dc.w    Track_SerpentAHymnToBacchus-TrackData
                dc.w    Track_Impulsefus7NewEntry-TrackData
                dc.w    Track_OpticSpankMyRedux-TrackData
                dc.w    Track_RaptureHurlyBurly64-TrackData
                dc.w    Track_PaulaHauntCarrotCakeRadio-TrackData
                dc.w    Track_ASIKWUSpulseGreenIsTheColor-TrackData
                dc.w    Track_AdamJJoyfulContinuation-TrackData
                dc.w    Track_WertstahlAlwaysAhead-TrackData
                dc.w    Track_SamplrStagnancy-TrackData
                dc.w    Track_WOTWHypnotized-TrackData
                dc.w    Track_OmniqNexus-TrackData
                dc.w    Track_GetafixMovesLikeJagger-TrackData
                dc.w    Track_TNKLockdownLiberation-TrackData
                dc.w    Track_CytronTheMoreThings-TrackData
                dc.w    Track_WeezerMelodieII-TrackData
                dc.w    Track_ComatronKISS-TrackData
                dc.w    Track_RemuteTheCarouselofRemute-TrackData
                dc.w    Track_WooberShortReturn-TrackData
                dc.w    Track_Ne7Banger-TrackData
                dc.w    Track_SlazeHypertension-TrackData
                dc.w    Track_TZXTheFleasGotTheCat-TrackData
                dc.w    Track_DannyMattissenTwistedEngine-TrackData
                dc.w    Track_GWEMTeaAtMidnight-TrackData
                dc.w    Track_tEISTurminchja-TrackData
                dc.w    Track_JuiceSpaceJam-TrackData
                dc.w    Track_Goto80Jeffrix-TrackData
                dc.w    Track_MisterRobotoLickMyBalls-TrackData
                dc.w    Track_MisterRobotoOutOfMyHouse-TrackData
                dc.w    Track_AkaobiRestlessBlipper-TrackData
                dc.w    Track_NOXW20M40M80P-TrackData
TracksE:


;-------------------------------------------------------------------------------
; Order must match directory table for music files
TrackData:

Track_GHIntroduction:
                dc.b    "GH - INTRODUCTION                     "
                dc.b    "WELCOME TO THE PIXELATED BEATS OF CHIP CHOP 17, BROUGHT TO YOU BY DESIRE! THE CHIPTASTIC TUNE YOU'RE GROOVING TO? THAT'S A CLASSIC GH CREATION FROM 2020, FINALLY GETTING ITS MOMENT TO SHINE IN THE LATEST SAGA OF OUR CHIP TUNE ANTHOLOGY. LET'S GET CHIP-FACED! MASSIVE THANKS TO ALL THE INCREDIBLE MUSICIANS WHOSE BEATS AND BYTES HAVE MADE THIS SEVENTEENTH EDITION OF CHIPCHOP BY DESIRE UTTERLY EPIC! YOUR TALENT AND DEDICATION HAVE TRULY SET THIS RELEASE APART. SHOUTOUT TO GIGABATES FOR THE SLICK CODING MAGIC AND TO LOWLIFE FOR THE EYE-CATCHING GRAPHICS THAT BROUGHT OUR VISION TO LIFE. WE ALSO HOPE THE DEMOSCENE AND CHIPTUNE COMMUNITY CAN FORGIVE RAMONB5 FOR HIS RELENTLESS, ALBEIT PASSIONATE, SPAMMING AND NAGGING TO HIT THE DEADLINE. IT'S ALL FOR THE LOVE OF THE SCENE! LET'S KEEP CREATING, SHARING, AND ENJOYING THE MUSIC THAT UNITES US. HERE'S TO MANY MORE! SOME WORDS FROM LOWLIFE NOW. I'M GRATEFUL TO BE THE BOD ROSS ARTIST AMONGST THE ESTEEMED GROUP OF MUSICIANS ON THE REVISION CHIP CHOP 17 RELEASE, DESPITE SOME DELAYS DUE TO LOGISTICAL ISSUES. ALL GRAPHICS WERE CRAFTED WITH BRILLIANCE ON THE 1200, DESPITE TARGETING OCS. SHOUTOUTS TO FELLOW SCENERS, MY UNDERSTANDING FAMILY, CURIOUS WORK FRIENDS, AND AXIS, MY COLLEAGUE. KEEPING IT BRIEF, I HOPE FOR MORE AMIGA RELEASES IN THE FUTURE. STAY TUNED FOR OUR VIC20 DEMO 'REVICION' AT REVISION. WISHING EVERYONE A JOYFUL REVISION, WHETHER ATTENDING IN PERSON OR FROM THE COMFORT OF THEIR SOFAS."
                END_TEXT
Track_BayTremoreOldTimes:
                dc.b    "BAY TREMORE - OLD TIMES               "
                dc.b    "WELCOME TO 'OLD TIMES' BY BAY TREMORE. IN A DIGITAL ECHO OF NOSTALGIA, I LET THE CHIPS DO THE TALKING. NO GRAND MESSAGES HERE, JUST THE PURE JOY OF CHIPTUNING, EXPLORING THE MAGIC WITHIN 4 CHANNELS. BIG THANKS TO THE DESIRE TEAM FOR THIS JOURNEY BACK TO BASICS. LET THE MUSIC OF 'OLD TIMES' TRANSPORT YOU, WHERE WORDS FALL SHORT BUT EMOTIONS RUN DEEP. ENJOY THE RIDE. BAY TREMORE."
                END_TEXT
Track_LaamaaSaintLager:
                dc.b    "LAAMAA - SAINT LAGER                  "
                dc.b    "THIS TUNE IS BEST SERVED WITH AN ICE COLD BEER. GREETINGS TO OSKILL8, D FAST, JONEZKY, PSG CABAL & CABINWAVE CREW."
                END_TEXT
Track_TobikomiNamkey:
                dc.b    "TOBIKOMI - NAMKEY                     "
                dc.b    "HELLO AMIGA ENTHUSIASTS. YOU GUYS LIKE NAMCO? 7650"
                END_TEXT
Track_AlpaandZiphoidAsWeRemain:
                dc.b    "ZIPHOID AND ALPA - AS WE REMAIN       "
                dc.b    "HI! ZIPHOID HERE. AS WE REMAIN... A LOOK INTO THE TOUGHER SIDE OF THE WORLD OF TODAY. WE HAVE LOST WAY TOO MANY GOOD PEOPLE IN THE LAST COUPLE OF YEARS THAT WE WANT TO CELEBRATE, BUT ALSO CELEBRATE ALL WHO ARE LEFT. ALPA AND I DECIDED TO DIG INTO THIS MUSICAL CHALLENGE TOGETHER AND WE HAD SO MUCH FUN DOING THIS! I HAVEN'T REALLY EVER RELEASED A PT MODULE, BECAUSE I'VE MOSTLY USED EITHER SOUND- OR NOISETRACKER OR SYNTHETIC TOOLS LIKE MUSICLINE, FREDED OR FUTURE COMPOSER, BUT I SURE HAD FUN. WE HOPE YOU'LL LIKE IT AS MUCH AS WE DO! HOPEFULLY THERE'LL BE MORE MUSIC IN THE FUTURE FROM ME. ALPA IS ALREADY A MUSIC-MAKING MACHINE, SO THERE'LL DEFINITELY BE MORE FROM HIM, NO DOUBT. ;) GREETINGS TO ALL MY FAMILY AND FRIENDS AND I'M SO SAD I COULDN'T MAKE IT TO REVISION THIS YEAR. AIMING FOR THE NEXT! OVER TO ALPA! --- HOWDY! ALPA HERE AT THE KEYS. THIS WAS MUCH FUN! ME AND ZIPHOID BOTH GOT INVITED TO CONTRIBUTE TO THIS MUSIC DISC AND ENDED UP COLLABORATING ON THIS TRACK. I DARE SAY WE ARE BOTH VERY HAPPY WITH IT AND BOTH GOT TO EXPRESS IN PARTS WHY MELODIES AND HARMONIES IS PART OF OUR DNA AND MAKE THE BEST DIARY. HOPE YOU ENJOY IT! I ALSO WISH TO SAY HI TO MY CREATIVE BOYS IN INSANE, MY AUDIO HEARTBEAT IN PROPER DISCO, BONEFISH, FIREFOX, JLD, TW1L1GHT, WIKLUND, MANTRONIX, SEFFREN, LOOPER231, JOGEIR, SLAYGON, ZIONA AND ACEDK. BE WELL, STAY CREATIVE AND DREAM BIG. /ALPA"
                END_TEXT
Track_CurtCoolBloatedColonel:
                dc.b    "CURT COOL - BLOATED COLONEL           "
                dc.b    "SCROLLING TIME AGAIN. OR. AT LEAST THIS IS CURT COOL WRITING, HAPPILY SAYING HELLO TO EVERYONE ON AND OFF REVISION 2024 A FEW WEEKS BEFORE THE ACTUAL EVENT. FOR NOW, I AM OLD AND TIRED AND CAUGHT UP IN WORK, HOPEFUL TO MAKE A TUNE OR TWO FOR THE REVISION COMPOS IF I FIND THE TIME AND ENERGY. MAYBE A FEW DAYS OF BEER AND SCENING WILL DO ME GOOD, EVEN AFTER ALL THESE YEARS? ANYWAY, ENJOY THE TUNE - HOPEFULLY NOT TOO WEIRD. YOU CAN ALSO WONDER WHICH NOVEL, THE TITLE COMES FROM (IT'S NOT OBVIOUS) - OR GO SPANK A SWIFTEE. REGARDS FROM CURT."
                END_TEXT
Track_GeminiDash:
                dc.b    "GEMINI - DASH                         "
                dc.b    "HELLO THERE! THIS IS GEMINI RETURNING FROM THE DEAD TO MAKE A NEW TUNE AFTER 5 YEARS. I AM VERY HAPPY TO BE PART OF THIS ALL NEW CHIPCHOP RELEASE! I HAD BEEN THINKING ABOUT MAKING ANOTHER MOD FOR QUITE SOME TIME, AND I MUST ADMIT IT FEELS GREAT TO GET INTO IT AGAIN! GREETINGS TO EVERYONE STILL AROUND AND KEEPING THE SCENE SPIRIT ALIVE! GEMINI SIGNING OFF.."
                END_TEXT
Track_AndyChypnotized:
                dc.b    "ANDY - CHYPNOTIZED                    "
                dc.b    "HEIDI-HO, THIS IS ANDY OF NUANCE AGAIN WITH A BRAND-NEW CHIPTUNE! IT HAS BEEN DECADES SINCE I TRACKED A CHIPTUNE ON THE AMIGA. BUT I REALLY ENJOYED DOING SO. IT WILL DEFINITELY NOT BE MY LAST ONE. I WOULD LIKE TO THANK DESIRE FOR THEIR GREAT CHIP CHOP MUSICDISC SERIES. GREETINGS ARE GOING OUT TO ALL MY DEAR SCENE-FRIENDS WITH WHOM I SPENT GREAT TIMES AND GREAT EVENTS DURING ALL THOSE YEARS. YOU ALL ROCK! FACE IT - YOU ARE ELITE ;-) ALSO ""HELLOS"" TO ALL VISITORS OF THIS YEAR'S REVISION, AND RESPECT AGAIN TO ALL ORGANIZERS AND HELPERS OF THIS GREAT SCENE-EVENT! LOOKING FORWARD TO MEET YOU ALL AT THE NEXT PARTIES AND SCENE-MEETINGS. KEEP ON BEING CREATIVE AND BLAST US AWAY WITH YOUR RELEASES. ALL THE BEST FOR YOU, YOUR FAMILIES AND FRIENDS. BYE FOR NOW. FRIENDSHIP ROOLZ & STAMPZ BACK! ANDY / NUANCE LOGGING OFF..."
                END_TEXT
Track_PunnikLies:
                dc.b    "PUNNIK - LIES                         "
                dc.b    "CAN YOU LOOK INTO MY EYES AND TELL ME THAT IT COMES AS A SURPRISE... IT'S TIME FOR YOU AND ME TO REALISE... WE ARE LIVING LIES... PUNNIK/KNP-REC."
                END_TEXT
Track_MaakQbix:
                dc.b    "MAAK - Q-BIX                          "
                dc.b    "IT'S MAAK AGAIN. I RECENTLY PLAYED RUBIK'S CUBE WITH MY SON, SO I MADE A SONG LIKE A PUZZLE GAME INSPIRED BY IT. I HOPE YOU ENJOY IT, EVEN THOUGH THE PRODUCTION TIME WAS SHORT AND THE SONG IS SHORT."
                END_TEXT
Track_VirgillKeygenX:
                dc.b    "VIRGILL - KEYGEN X                    "
                dc.b    "IN SHADOWED CORNERS OF THE DIGITAL DOMAIN, WHISPERS ECHO OF A HACKER'S REFRAIN. CRACKS AND KEYGENS, CLANDESTINE TOOLS, UNVEILING SECRETS, BREAKING DIGITAL RULES"
                END_TEXT
Track_Soda7Appeal:
                dc.b    "SODA7 - APPEAL                        "
                dc.b    "SODA7 ON THE KEYS. THIS IS MY CONTRIBUTION TO THE MUSICDISK, AS I WANTED TO WRITE SOMETHING AS A NOD TO 90S AMIGA CHIPTUNES, PARTICULARLY TO THE STYLES OF BRITISH MUSICIANS SUCH AS TDK AND 4MAT. GREETS TO ALL THE AMIGA AND DEMOSCENE PEOPLE STILL ROCKIN, YOU'RE TOO MANY TO MENTION! REVISION IS THE FIRST DEMOPARTY I'M EVER ATTENDING, AFTER TELLING MYSELF TO VISIT A DEMOPARTY FOR LIKE MORE THAN 15 YEARS - ABOUT TIME I'D SAY! IF YOU WANT TO CONTACT ME YOU CAN EIGHTER REACH ME ON THE USUAL DEMOSCENE CHANNELS YOU ALL KNOW, OR BETTER, YOU CAN GIVE A CALL TO THE ABSINTHE BBS VIA TELNET - ABSINTHEBBS.NET PORT 1940! YEP, AS YOU CAN SEE, BBS ARE STILL RUNNING TODAY, AND ABSINTHE IS PERHAPS ONE OF THE BEST BOARDS STILL RUNNING TODAY - WITH UP TO DATE DOOR GAMES, MESSAGE BOARDS, FILE ARCHIVES, GREAT AMIGA ANSI ART BY THE SYSOP ANACHRONIST - AND EVEN BETTER, THIS BOARD IS RUNNING ON A REAL AMIGA MACHINE! SO, WRAPPING IT OFF, ENJOY THIS MUSICDISK AND SEE YOU AROUND!"
                END_TEXT
Track_TurboKnightRaptureLongtime:
                dc.b    "TK & RAPTURE - LONG TIME NO CHIP      "
                dc.b    "I HAD A LITTLE 15 YEAR BREAK ON MAKING CHIPTUNES BUT NOW I'M BACK WITH A COLLAB WITH RAPTURE! GREETZ GOES TO ALL THE DESIRE PEEPS AND EVERYONE WHO WORKED ON ENCORE 500. WE JUST MIGHT HAVE ANOTHER COMPILATION AT WORKS WITH MOSTLY THE SAME PEOPLE SO GET READY FOR SOME INSANE RETROREMIXES! I ALSO WANT TO WISH GREAT TIME FOR ALL THE REVISION'24 VISITORS, HAVE A BLAST. TK OUT..."
                END_TEXT
Track_NotoriousMittenSmitten:
                dc.b    "NOTORIOUS - MITTEN SMITTEN            "
                dc.b    "HELLO FROM NOTORIOUS, HAPPY TO CONTRIBUTE FOR SUCH A NICE SERIES LIKE CHIP CHOP! I DON'T KNOW ABOUT YOU GUYS BUT I FEEL LIKE TIME IS MOVING FASTER THESE DAYS, IT'S ALREADY EASTER AGAIN. I HOPE YOU ALL FEEL AS I FEEL THAT THE AMIGA IS RISING AGAIN SINCE THE PRODUCTIONS ARE JUST BECOMING BETTER AND BETTER! I HOPE TO SEE YOU AT ANY OF THE UPCOMING PARTIES THIS YEAR! CHEERS TO ALL YOU FRIENDS AND SCENERS OUT THERE."
                END_TEXT
Track_XYCELeCourant:
                dc.b    "XYCE - LE COURANT                     "
                dc.b    "HEYYO PARTY PEOPLE! XYCE HERE, OR XYLO AND CERROR IF YOU PREFER IT THAT WAY. THIS IS OUR FIRST NEW TUNE SINCE AGES BECAUSE OF THE LACK OF FREE TIME AND MOSTLY WRITERS BLOCK. BUT AFTER WEEKS OF PERSEVERANCE AND MOSTLY PROCRASTINATION WE'VE FINALLY MANAGED TO MAKE ONE. ENJOY! GREETS GO OUT TO ALL THE OTHER ARTISTS THAT HELPED WITH THIS FINE MUSIC DISC. ALSO GREETINGS AND LOVE TO ALL THE OTHER (CHIPTUNE) ARTISTS WE'VE MET OR SPOKEN TO IN THE LAST 20 YEARS, DEMOSCENE OR OTHER. ALSO SHOUTOUT TO YOU, THE LISTENER, FOR STILL LISTENING TO YE OLD AMIGA TUNES! PEACE OUT"
                END_TEXT
Track_OkeanosTheDawnSkies:
                dc.b    "OKEANOS - THE DAWN SKIES              "
                dc.b    "BEFORE THE WORLD, COMES DAWN. COPPER COLORS SPLASHING HUES UPON THE SKIES. THIS MOMENT WHEN ANYTHING COULD BE DONE. JUST BEFORE THE SUN RISES. BEFORE THE MUSIC, COMES THE MELODY. NOTES JOSTLING IN MY HEAD. THIS MOMENT WHEN YOU FIND YOUR IDENTITY. TO COMPOSE, TO SHARE AND SPREAD. ASSEMBLING CHIPS AND BITS. CREATING MY OWN WORLD. A WORLD WHERE EVERYTHING COULD FIT. THAT'S MY WORD. THAT'S MY AIM. THAT'S MY CLAIM. OKEANOS/TEK SIGNING OFF"
                END_TEXT
Track_RobynPurplelily:
                dc.b    "ROBYN - PURPLELILY                    "
                dc.b    "ORIGINALLY STARTING OUT AS A SHORT SKETCH TO BE PORTED TO AHX, I WAS REALLY HAPPY WITH HOW I GOT IT SOUNDING AS A MOD. THE ATMOSPHERE FELT RIGHT WITH THE SAMPLED CHORDS, AND I DECIDED TO EXTEND IT FOR CHIP CHOP. THE SONG TITLE IS A REFERENCE TO AN ALIEN GIRL FROM THE SERIES MAO-CHAN. THANKS FOR LISTING, AND MANY THANKS TO DESIRE FOR INVITING ME!"
                END_TEXT
Track_EarthlingTwoTrackWonder:
                dc.b    "EARTHLING - TWO TRACK WONDER          "
                dc.b    "EARTHLING FROM WET ELECTRONICS SENDS GREETINGS TO PSYCHE OF RAPTOR AND D-ZIRE OF SILENTS AND THE GOOD FOLK OF DESIRE. THIS TRACK IS ENTIRELY COMPOSED IN ONLY TWO TRACKS. INSTRUMENTS RENDERED IMPULSE LOADED THROUGH FASTTRACKER TO PROTRACKER V2."
                END_TEXT
Track_TeconEngage:
                dc.b    "TECON - ENGAGE                        "
                dc.b    "GREETINGS FELLOW CHEESE LOVER! YOUR STOMACH MUST BE FULL OF JOY NOW AFTER LOADING ANOTHER EDITION OF CHIPCHOP?! I HOPE MY LITTLE CONTRIBUTION HERE DOES NOT FOUL THE FLAVOUR. A SPECIAL GREETING TO SCOURGER AND STRIPE THE GREMLIN OF TALENT FOR GIVING ME A LIFT TO GERP THIS YEAR.. AND TO EVERYONE I MET THERE I WANNA SAY THANKS FOR THE MOMENTS! LAST NOTE: JOIN THE PT-WEEKENDER STREAM AT TWITCH ON APRIL 19TH AND 20TH FOR AN EXTRAORDINARY EXPERIENCE, AND CHECK OUT AMIGADJ.COM FOR A BUNCH OF PAST MIXSETS... ALOHA FROM NORWAIi, TECON SIGNING OFF."
                END_TEXT
Track_NeuroflipFreeCarmela:
                dc.b    "NEUROFLIP - FREE CARMELA              "
                dc.b    "HOLA REVISION! NEUROFLIP OF OBSOLETE HERE CONTRIBUTING TO THIS GREAT MUSIC DISK WITH A HAPPY AND RELAXING MOD. DEDICATED TO CARMELA AND PACO. ONE BIG LOVE AND GOOD VIBES TO YOU ALL AT REVISION AND ALL THE PEOPLE AT THE SPANISH SATELLITE EVENT."
                END_TEXT
Track_mA2EAuroraNights:
                dc.b    "MA2E - AURORA NIGHTS                  "
                dc.b    "HEY. MA2E HERE. AFTER RAMON PESTERED ME LONG ENOUGH, I FINALLY MANAGED TO CREATE A SCROLL TEXT. SO MANY YEARS AFTER THE PREVIOUS RELEASE OF CHIPCHOP, 9 YEARS SINCE THE LAST ISSUE, NUMBER 17 IS HERE. IT'S THE FIRST TIME I HAVE HAD THE OPPORTUNITY TO BE PART OF THIS PROJECT, AND I AM FAR FROM THE ONLY ONE. 75 OTHER TRACKS, IN THE SAME CHIPPACK, IT'S QUITE INCREDIBLE. SOME QUICK SALUTATIONS TO MY FRIENDS IN  FATZONE, MOODS PLATEAU, RESISTANCE, AND PROXIMA.., ALSO A BIG GREETINGS AND THANKS TO MY WIFE WHO LET ME SIT HOURS AFTER HOURS COMPOSING. AND ALSO AS MENTIONED BEFORE, THANKS TO THE WHOLE AMIGA COMMUNITY AND THEIR SUPPORT AND INSPIRATION. WITHOUT YOU, I WOULD HAVE STOPPED MAKING MUSIC MANY MANY YEARS AGO. THAT IS ALL FROM ME, NOW GO AND LISTEN TO THE OTHER TUNES. MAZE OUT."
                END_TEXT
Track_RaptureSpaceRatatouille:
                dc.b    "RAPTURE - SPACE RATATOUILLE           "
                dc.b    "HI! RAPTURE AGAIN! OF COURSE THERE IS ANOTHER MODULE OF MINE IN THE WONDERFUL CHIPCHOP17 COLLECTION! SPACE RATATOUILLE IS DELICIOUS, ENJOY! P.S. IF YOU CAN, PLEASE JOIN AND SUPPORT ME ON MY PATREON. EVERY LITTLE BIT HELPS! THANKS A LOT FOR YOUR SUPPORT IN ADVANCE! PATREON.COM/FABIAN_DEL_PRIORE"
                END_TEXT
Track_OctapusAstroSwong:
                dc.b    "OCTAPUS - ASTRO SWONG                 "
                dc.b    "MAKE IT SWING, MAKE IT SWONG! BIG UP UP ROUGH! SHOUT OUT TO RATVADER FOR ALL THE GREAT COLLABORATIONS. PARTS OF THIS TUNE WERE USED IN A TRACK ON HELLO WORLD'S 10TH ANNIVERSARY VINYL. CHEERS TO YOU ALL!"
                END_TEXT
Track_NoolyGoodTimesAreNow:
                dc.b    "NOOLY - GOOD TIMES ARE NOW            "
                dc.b    "IS IT REALLY 25 YEARS I'VE BEEN PART OF THE SCENE? TIME SURELY FLIES AND I LEARNED A LOT OF THINGS, MOST OF THEM THE HARD WAY. I GREET FELLOW CZECHS AT THE REVISION PARTY AND ALL PEOPLE WITH A GOOD HEART. ENJOY THE PARTY AND DRINK RESPONSIBLY. BELIEVE ME, I WISH SOMEONE GAVE ME AN ADVICE LIKE THAT IN THE PAST! VOJTA"
                END_TEXT
Track_YziEnnenolichipitrautaa:
                dc.b    "YZI - ENNENOLICHIPITRAUTAA            "
                dc.b    "FROM THE CREATIVE MIND OF YZI COMES A CLASSIC MELODY TITLED ""ENNEN OLI CHIPIT RAUTAA,"" CRAFTED WITH MILKYTRACKER TO ANDHARMONIZED SEAMLESSLY WITH THE AMIGA. POSSESSING NOT ONE, BUT FOUR AMIGAS, YZI DECIDED IT WAS HIGH TIME THESE MACHINES WERE AWAKENED FROM THEIR SHELF-BOUND SLUMBER FOR A TRUE SONIC ENDEAVOR. THIS PIECE, A LABOR OF LOVE COMPLETED A FEW YEARS PRIOR, IS YZI'S CONTRIBUTION TO THE DESIRE TEAM AND THE SEVENTEENTH INSTALLMENT OF CHIP CHOP. DIVE INTO THIS MUSICAL JOURNEY, AND MAY YOU FIND PLEASURE IN THE RESULT OF THIS NOSTALGIC ENDEAVOR"
                END_TEXT
Track_DvibeHalvTreKaffet:
                dc.b    "DVIBE - HALV TRE-KAFFET               "
                dc.b    "THIS SONG IS ABOUT A SUNDAY AFTERNOON HAVING A CUP OF COFFEE AT HALF PAST 2. THE WINTER IS GRAY BUT BIRDS ARE CHIRPING OUTSIDE KEEPING THE MOOD UP A LITTLE BIT. THIS BITTERSWEET FEELING OF BEING SOMEWHERE COZY WHILE AVOIDING TO THINK OF WHAT NEEDS TO BE DONE ON MONDAY MORNING AND AT THE SAME TIME FEELING THE CAFFEINE KICK IN. THE STRINGS IN THE BEGINNING OF THE SONG ARE UNCLEAR IF THEY ARE OUT OF TUNE OR NOT, AND IT'S LIKE A GHOST FROM THE PAST SINGING WHERE ITS VOICE'S OVERTONES ARE BLENDING IN TO THE FUNDAMENTAL TONE A BIT TOO MUCH. LIFE IS ALSO A BIT UNCLEAR FROM TIME TO TIME. WHO KNOWS WHAT THE GHOST WANTS TO SAY? MORE MUSIC AT WWW.DVIBE.SE D VIBE'S / SAGTAND'S MUSIC & OTHER SNACKS"
                END_TEXT
Track_Ne7FridayFeelin:
                dc.b    "NE7 - FRIDAY FEELIN                   "
                dc.b    "BIG HUGS TO THE ONES KEEPING THE SCENE ALIVE IN 2024, MODULES AND SAMPLING IS WHERE ITS AT AND AMUSINGLY MOST OF THE KIT FOCUSSED NUSCHOOL PEEPS SEEM TO HAVE WOKEN UP TO THE JOYS OF OLD SAMPLE CDS AND OUTBOARD SAMPLING KIT A LOT MORE AS OF THIS YEAR WHICH DOES MAKE ME CHUCKLE: SOME OF US NEVER STOPPED. BIG LUV TO ME TEAM MATES IN 3LN, DIVINE STYLERS, DUAL CREW SHINING, NAPALM, REBELS, RETROGURU, SCOOPEX, TRIAD & UKSCENE ALLSTARS!"
                END_TEXT
Track_TriaceUplifter:
                dc.b    "TRIACE - UPLIFTER                     "
                dc.b    "YO TRIACE ON THE KEYS JUST TYPING IN SOME NONSENSE TO WASTE YOUR TIME WHILE YOU ARE PROBABLY LISTENING TO SOME EAR DEFYING BLEEPS MADE BY YOURS TRULY, THIS TIME FROM THE UPLIFTING SIDE OF THE HARMONY SCALE. ENJOY EASTER, SPRING, LIFE, THE UNIVERSE AND EVERYTHING. AND ALWAYS REMEMBER: ITS NICE TO BE IMPORTANT, BUT ITS MORE IMPORTANT TO BE NICE - PERSONAL GREETINGS TO ALL I KNOW ESPECIALLY ALL DESIRED PANDAS, INSANE INSANERS AND REDFLASHING RETROGURUS, VIRGILL, DASCON, OZAN, LMAN, TEO, CHROMAG AND THE REST OF THE BUNCH. SEE YOU AROUND AND KEEP THE BLEEP. CHEERS TO EVERYONE CONTRIBUTING PULLING ANOTHER CHIP CHOP OFF"
                END_TEXT
Track_UctumiDisqualified:
                dc.b    "UCTUMI - DISQUALIFIED                 "
                dc.b    "WHERE THERE'S A NEED, THERE'S THE RIGHT TO MAKE SOMETHING ABOUT IT"
                END_TEXT
Track_UlrickMachineras:
                dc.b    "ULRICK - MACHINERAS                   "
                dc.b    "AT THE END OF THE 1980S, A FEW PIONEERS PAVED THE WAY FOR AMIGA TRACKED MUSICS. GREETZ TO 'EM AND TO DESIRE FOR GIVING ME THE OPPORTUNITY TO CONTRIBUTE TO CHIP CHOP #17. DUE GREETINGS ALSO GO TO XOOFX FOR HIS INSIGHTS ON .MOD SAMPLE RATES, BEXXX & HEPTERIDA WHO GIVE A BREATH OF LIFE TO FRQ. DO YOU LIKE ANAGRAMS? BY REMOVING 'E,' THE ANAGRAM OF MACHINERAS IS ... THE TUNE USES SAMPLES FROM SEVERAL SOURCES: AUDACITY TONE GENERATOR, LOOPMASTERS' COIN-OP CHIPTUNE, ST-65 CHIPSYN' AND A SAMPLE FROM PART-3-SND.MOD' BY STEEL HERTZ"
                END_TEXT
Track_NoXSAtChoic3:
                dc.b    "NO-XS - ATCHOIC3                      "
                dc.b    "HELLO! THIS IS NO-XS. NOW YOU KNOW ME! I HOPE YOU ENJOY THIS LITTLE SONG. THE CHORDPROGRESSION WAS MADE BY ELLIE DIXON (IF I REMEMBER IT RIGHT) AND NOT LEFT MY HEAD. ALMOST ALL MY MODS WERE GONE WITH A HD CRASH, BUT RAMON KEPT A COPY OF THIS ONE! GREETS TO MY FELLOW DSR MEMBERS AND TO EVERYONE IN THE SCENE THAT I KNOW. AND TO ALL I DON'T KNOW"
                END_TEXT
Track_JosssMoonshiner:
                dc.b    "JOSSS - MOONSHINER!                   "
                dc.b    "CHIP CHOP, CHIPPY CHIPPY HOP! JOSSS WHISTLING SOME HAPPY LINES TO SEND BIG ABRAZOS TO THE CHIPTUNE SCENE AND SPECIALLY TO THE REST OF THE CREW INVOLVED IN THIS NICE DESIRED PROJECT. CHEERS FROM MADRID AND KEEP THE AMIGA TRACKER SCENE ALIVE!!!"
                END_TEXT
Track_HyperunknowGoatFiction:
                dc.b    "HYPERUNKNOW - GOAT FICTION            "
                dc.b    "HEYOOO HYPERUNKNOWN OF NOICE ON THE KEYS .. I WOULD LIKE TO TAKE THIS OPPORTUNITY TO THANK EVERYONE WHO IS STILL CODING, MAKING GRAPHICS AND COMPOSING MUSIC ON THE AMIGA AND PC, KEEPING THE DEMOSCENE ALIVE, YOU ARE THE PEOPLE I ALWAYS LOOKED UP TO EVEN SINCE I WAS A KID .. KEEP CALM AND MOV AX"
                END_TEXT
Track_AlexMenchiWelcomeToTheParty:
                dc.b    "ALEX MENCHI - WELCOME TO THE PARTY    "
                dc.b    "OH MY GOD...! WHAT A PLEASURE TO BE HERE WITH YOU TO LISTEN TO THIS DISK, WHICH BRINGS TOGETHER SO MANY TALENTED PEOPLE WHOM I ADMIRE. THANK YOU TO DESIRE FOR ALL THE WORK AND TIME SPENT ON THIS NEW OPUS. GREETZ TO FRA, GUNHED, H0FFMAN, JIM NERAY, K1200RS21, OK3ANOS, NLK, SOUNDY, TONI GÁLVEZ, TYPHOON, VIGILL, VOXEL. MY ONLY RECOMMENDATION: TURN ON YOUR AMIGA AT LEAST ONCE A DAY: A FRIEND FOR LIFE!"
                END_TEXT
Track_GouafhgBrendaandDylan:
                dc.b    "GOUAFHG - BRENDA AND DYLAN            "
                dc.b    "SO HERE IS GOUAFHG AT THE KEYS - HI THERE! I JUST FINISHED WATCHING A 5 AND A HALF PERIOD LONG ICE HOCKEY GAME WHERE MY TEAM LOST :-( BETTER LUCK NEXT TIME! SO WHAT ABOUT THIS TUNE THEN? I BEGAN GROWING THE IDEA SOME TIME AGO. WHEN THINKING OF WHAT TO WRITE ABOUT I HAD A FLASHBACK OF THE AWESOME INTRO OF THE BAYWATCH MOVIE! THEN I CHECKED IT OUT AND DANG THAT SONG WAS WHAT MY HEAD STARTED BREWING ABOUT. A BEAT CAME UP AND I FIDDLED A BIT WITH SOME POCKET OPERATOR BEATMACHINES FOR A FEW WEEKS UNTIL I HAD A BIT LESS OF WORK HOLDING ME BACK. SO CAME THAT DAY WHEN I STARTED TRACKING IT DOWN ABOUT A WEEK BEFORE DEADLINE. I HAD THE OUTLINE OF THE BEAT AND INTRO. BUT WHO WANTS TO LISTEN TO A SONG WITH A SLOW START ON A MUSIC DISK!? NOT ME? SO IT HAD TO START KIND OF RIGHT AWAY. ALONG CAME SOME MELODIES AND SOME KIND OF BRIDGE PART. HOWEVER, WHEN I LISTENED IT FELT LIKE THE SONG ACTUALLY BEGAN WHEN THE THING I HAD THOUGHT OF AS A BRIDGE. SO OFF WE GO! I REWROTE THE BEAT TO GET THE ENERGY KIND OF KICKING WITH THAT ONE. IT ALSO NEEDED SOME MELODY, WHICH KIND OF INTUITIVELY GOT TO ME... AT ONCE! THEN I LOOKED BACK AT THE FIRST PART. WHAT TO DO WITH IT. THE MELODIES WAS LIKE A BIT MESS. THERE WERE HINTS OF SOME KIND OF MOTIF, BUT MOSTLY.... A MESS! THE DEADLINE APPROACHED QUITE FAST SO I DIDN'T HAVE A LOT OF TIME TO LET IT DWELL AND BREW, HENCE I DID THE TOTALLY WRONG THING AND BEGAN PUSHING MY 10 CHANNEL MUSIC INTO THE 4 REAL CHANNELS WHILE IT ALL FELT LIKE I WAS GOING LOST. HOWEVER, AFTERWARDS, I THINK I GOT A SENCE OF WHAT THE CORE IN ALL THAT MESS WAS AND TRIED TO EXTRACT IT AND REFINE THE PART. AFTER A WHILE I FELT THAT THE TRY KIND OF SUCCEEDED AND MOVED ON TO MAKE SOME BREAKS BETWEEN THE PARTS. SONG DONE! SO, DEADLINE IN A COUPLE OF HOURS AND THE SONG RUNS IN AT 70K! REMOVE SOME JUNK SAMPLES AND WE ARE AT 56K. NEED TO GET DOWN TO... 30? GET THE SAMPLES OF THE BEAT IN LOWER QUALITY? SURE! I WOULD HAVE LIKED TO SEARCH FOR BETTER SAMPLES WITH SMALLER FOOTPRINT AND REWRITE THE BEAT USING THEM, BUT NO TIME FOR THAT! I GET IT TO AROUND 45K AND TRY WHAT IT WOULD LOOK LIKE AFTER A P61 CONVERSION. 25K! THE PATTERN DATA ALONE WAS AROUND 20K, SO I HAVE LOW HOPES OF GETTING IT LOWER THAN THAT. I GIVE UP AND GIVE IT AWAY HOPING IT FITS THE COLLECTION. AND IF YOU READ THIS, I GUESS IT DID!"
                END_TEXT
Track_TFXWillows:
                dc.b    "TFX - WILLOWS                         "
                dc.b    "INSPIRED HEAVILY BY MUSEUM OF UNNATURAL DISASTERS / HALLEY LABS. IT'S BEEN A WILD FEW YEARS BUT THE WIND IS IN MY SAILS. SHOUTS TO HIIJ, ZOPE, VLK, AYCE, TITAN, AND ALL THE COOL PEOPLE ON THE SCENE!"
                END_TEXT
Track_DusthillresidentTetsujin:
                dc.b    "DUSTHILLRESIDENT - TETSUJIN           "
                dc.b    "BIG THANK YOU RAMON FOR FEATURING ME ON THIS MUSIC DISK! I'D LIKE TO GIVE A SHOUT OUT TO MY BEST FRIEND ROBYN A1200 WHO'S ALSO ON THIS DISK! SHE HELPED ME SO MUCH WITH THE PRODUCTION ON THIS SONG, HER AMIGA 4CH SKILLS ARE UNRIVALLED!! WITH THIS SONG I WANTED TO MAKE SOMETHING CHILL AND RELAXING, INSPIRED BY AMIGA AND SUPER FAMICOM TUNES I LISTENED TO SO MUCH AS A YOUNG TEEN. I THINK I SUCCEEDED AT GETTING THE NOSTALGIC FEEL I WAS LOOKING FOR. THANK YOU FOR LISTENING!"
                END_TEXT
Track_SlashFillingItUp:
                dc.b    "SLASH - FILLING IT UP                 "
                dc.b    "HELLO SLASH ON THE KEYS, WELCOME TO MY TUNE! THIS SONG WAS CREATED SOME YEARS AGO TO SUPPORT THE GREAT CHIP CHOP SERIES. GREETINGS TO MY FRIENDS IN THE DEMOSCENE. KEEP IT UP! / SLASH"
                END_TEXT
Track_Buddy105Fahrenheit:
                dc.b    "BUDDY - 105 FAHRENHEIT                "
                dc.b    "BUDDY HERE!!! I AM PROUD TO HAVE BEEN ASKED IF I WOULD LIKE TO TAKE PART IN THIS CHIPCHOP!!! THANKS TO THE DESIRE TEAM FOR YOUR TRUST!!! BACK IN THE 90S I TRIED TO MAKE 2-3 CHUPTUNES, BUT TODAY I MAKE MORE SONGS FOR THE POKEY (ATARI 8-BIT)!!! CHECK OUT MY YOUTUBE CHANNEL!!! JUST SEARCH FOR: BUDDY76CD IF I CAN, I'M ALREADY LOOKING FORWARD TO THE NEXT CHIPCHOP MUSIC PACK THAT I CAN BE INVOLVED IN!!! YOUR BUDDY"
                END_TEXT
Track_QwanTatsunokoLandscape:
                dc.b    "QWAN - TATSUNOKO LANDSCAPE            "
                dc.b    "THIS SONG WAS FIRST RELEASED IN THE SNES MUSIC COMPO 2009. I ALWAYS THOUGHT THIS TUNE WOULD FIT A DEMO OR INTRO WITH A STORY LIKE THE VIDEOS FOR DAFT PUNK'S DISCOVERY ALBUM. ENJOY!"
                END_TEXT
Track_MaakInMyMemories:
                dc.b    "MAAK - IN MY MEMORIES                 "
                dc.b    "HI, I'M MAAK, FROM JAPAN AND I'M VERY HAPPY TO BE ABLE TO PARTICIPATE IN THE AMIGA DEMOSCENE! "
                dc.b    "THANKS TO DESIRE FOR INVITING ME! MY FIRST ENCOUNTER WITH THE AMIGA/PC TRACKER CHIPTUNE HAS "
                dc.b    "INSPIRED ME TO CONTINUE MAKING CHIPTUNES TO THIS DAY. THANKS TO ALL THE LEGENDARY COMPOSERS "
                dc.b    "WHO WERE MAKING CHIPTUNE BACK THEN. I AM CURRENTLY WORKING ON A C64 SID ALBUM, SO IF YOU WOULD "
                dc.b    "LIKE TO FOLLOW ME ON SOUNDCLOUD AND SNS, I WOULD BE HAPPY TO HEAR FROM YOU."
                END_TEXT
Track_MrGamerChipex5:
                dc.b    "MRGAMER - CHIPEX 5                    "
                dc.b    "HEY Y'ALL, MRGAMER OF MOONSHINE HERE! VETERAN SCENER AND PROFESSIONAL CRAZY PERSON. IT WAS TOTALLY AWESOME OF DSR TO INCLUDE MY TUNE IN THIS PACK, BUT DAMN, I'M GLAD THEY DID! THIS IS FREAKING SWEET... OH, ALSO, GOOGLE ME TO FIND TONS AND TONS MORE OF MY MUSIC. I'LL BE WAITING FOR YOU ALL ON YOUTUBE AND SPOTIFY! CHEERS!/ ANDREAS ROHDIN"
                END_TEXT
Track_SerpentAHymnToBacchus:
                dc.b    "SERPENT - A HYMN TO BACCHUS           "
                dc.b    "QUITE A SILLY SONG I MADE SOME YEARS AGO. THE TITLE DOESN'T MEAN BACCHUS/FAIRLIGHT, BUT THE GOD OF WINE, FERTILITY AND SO ON AND IT'S ALSO A 'FUN' WORDPLAY WITH MY OLDER TUNE WHICH WAS IN 'A HYMN TO HIPPARCHUS' AMIGA 4K MADE BY NOSFERATU/OFFENCE. THE STRANGE PARTS SHOULD RESEMBLE A PHONE CALL TO WIFE WHILE DRUNKEN AND WIFE YELLS AND TELLS ME TO GO XXXX MYSELF. GREETINGS TO FRIENDS, SPECIAL GREETS TO RAPTURE BECAUSE I FORGOT TO GREET HIM ON STAGE AT ASSEMBLY 2019 WHEN WE WON THE TRACKING COMPO, AND HE ALWAYS NAGS ME ABOUT THAT. THAT'S ABOUT IT FOLKS"
                END_TEXT
Track_Impulsefus7NewEntry:
                dc.b    "IMPULSEFUS7 - NEW ENTRY               "
                dc.b    "HI EVERYONE! THIS IS IMPULSEFUS. THIS IS A LITTLE TUNE I WROTE FOR THIS MUSIC DISK IT'S CALLED 'NEW ENTRY' AND IT'S AROUND 30K I DECIDED TO ADD SOME CHORD SAMPLES FOR A BIT OF UNIQUENESS AND TO SEE HOW MUCH I COULD CRAM IN SUCH RELATIVELY SMALL SPACE ENJOY!"
                END_TEXT
Track_OpticSpankMyRedux:
                dc.b    "OPTIC - SPANK MY REDUX                "
                dc.b    "I DON'T OFTEN WRITE SCROLLTEXTS THESE DAYS, BUT WHEN I DO (INSERT MEME)... OPTIC ON THE KEYS. JUST A QUICK LITTLE SOMETHING-SOMETHING TO GO WITH THE TUNE, IF YOU CAN CALL IT THAT. THIS IS A REMIX OF AN OLD CHIPTUNE I DID BACK IN THE NINTIES, WHICH SEEMS TO BE WHERE MOST OF MY TRACKING IS THESE DAYS. NO RECOLLECTION OF WHAT THE ORIGINAL TUNE WAS INTENDED FOR, BUT FAST FORWARDS 15-20 YEARS AND BOOZOMBIES NEEDED A FEW TRACKS FOR A 64KB INTRO. SO I REWORKED THIS AND A FEW OTHERS FOR SAID PRODUCTION, HENCE THE REDUX. FAST FORWARDS 10 YEARS AND M'MAN RAMONB5 NEEDS SOME MUSIC FOR THE NEXT EDITION OF CHIPCHOP, AND UPON REVIEW, THIS WAS THE ONLY THING I HAD THAT WAS REMOTELY READY. I AM ASSUMING (MAKING AND ASS OUT OF YOU AND MING THE MERCILESS), 10 YEARS IS A LONG ENOUGH TIME FOR A LITTLE RE-RELEASE. IF NOTHING ELSE, IT HAS SPURRED ME ON TO DIG OUT THE OLD TRACKER AGAIN, SO MAYBE.. JUST MAYBE.. THERE WILL BE SOMETHING NEW ONE OF THESE DAYS... (I VERY MUCH TRACK BY WAY OF THE INFINITE MONKEY THEROREM... SO EVENTUALLY ONE IS BOUND TO STICK). GREETINGS TO EVERYONE OUT THERE! IF YOU'VE READ THIS FAR, YOU'VE LISTENED TO ENTIERLY TOO MUCH OF THE TRACK. PEACE OUT! MUCH LOVE!"
                END_TEXT
Track_RaptureHurlyBurly64:
                dc.b    "RAPTURE - HURLY BURLY 64              "
                dc.b    "HI, RAPTURE SPEAKING HERE! I'M HONORED TO BE ON THE CHIPCHOP17 RELEASE. NORMALLY I WRITE TRACKER "
                dc.b    "MODULES IN MILKYTRACKER, SO DOING MODULES IS QUITE AN EXPERIENCE TO MAKE WITH THE PROTRACKER AMIGA "
                dc.b    "LIMITATIONS! HOPE YOU ENJOY THE MUSIC! WRITE ME FOR ANY FRIENDLY AND MUSICAL REASON! YOU CAN FIND "
                dc.b    "ME ON THE NECTARINE DEMOSCENE RADIO, THE BEST ONLINE RADIO EVER! JOIN US AND START TO CHAT WITH US! "
                dc.b    "GREETINGS TO ALL DEMOSCENERS! CHEERS, RAPTURE"
                END_TEXT
Track_PaulaHauntCarrotCakeRadio:
                dc.b    "PAULA HAUNT - CARROT CAKE RADIO       "
                dc.b    "GREETS TO THE WAFFLE CREW, GREETS TO MY GREAT RED HOMIES! HELLO TO MARK SALUD! GREETS TO ALL MUSICIANS, ARTISTS, AND CODERS TAKING PART IN CHIP CHOP 17! BIG THANKS TO RAMONB5 AND DESIRE FOR ALLOWING ME TO BE A PART OF THIS. LAST BUT MOST IMPORTANT, A SPECIAL SHOUT OUT TO MY NIECE, NELLIE! NO ST-XX SAMPLES WERE HARMED IN THE MAKING OF THIS CHIPTUNE."
                END_TEXT
Track_ASIKWUSpulseGreenIsTheColor:
                dc.b    "ASIKWUSPULSE - GREEN IS THE COLOR     "
                dc.b    "HEY THERE CHIP CHOP 17 LISTENER! THIS IS ASIKWUSPULSE WRITING, AND THE TUNE YOU ARE HEARING RIGHT NOW IS MY WORK FOR THIS COMPILATION (AND I THINK IT COUNTS AS MY FIRST EVER WORK FOR THE DEMOSCENE?). IT'S 2024 WHEN I'M WRITING THIS, AND THIS TUNE WAS FINISHED BACK IN 2021. I WEREN'T TOO FAMILIAR WITH THE AMIGA MOD FORMAT BACK THEN, AND I REMEMBER IT WAS A BIT OF A CHALLENGE TO COME UP WITH SOMETHING, ESPECIALLY WHEN CHIP CHOP IS CHIPTUNE, AND THAT THE MODULE HAS TO BE MAX BETWEEN 20-30 KB. I WASN'T GONNA PASS UP THE OPPORTUNITY, AND I LET THE IDEAS COME NATURALLY. I HAD WRITTEN SOME CHIPTUNES BEFORE IN IT FORMAT IN A SMALL PROJECT I CALL FREEDRIVE CHIPTUNE, WHERE I RATHER THAN CHIP-WAVEFORM SAMPLES USE BYTE-SAMPLES (THEY'RE SIMILAR IN SIZE, BUT THE SAMPLE HAS AN ATTACK PORTION BEFORE THE LOOP). I THINK THAT ALONG WITH MY STYLE THAT IS KINDA A MIX OF SOUND-ADOPTIONS FROM MUSIC I LISTEN TO, AMONG WHICH TRACKER MUSIC IS PRESENT, IS THE APPROACH I HAD FOR THIS TUNE. I THINK YOU CAN NOTICE THAT I HAVE A STRONG TASTE FOR FUNK AND JAZZ-FUSION, EVEN THOUGH I LIKE A LOT OF GENRES LIKE METAL, ROCK, POP, ETC. WHAT I'VE RECENTLY HEARD CAN BE DEFINED AS A MUSIC OMNIVORE HAHA! BUT I TEND TO MOST OF THE TIMES NOT GET SATISFIED WITH JUST THE SIMPLE SOUND. I LIKE TO SPRINKLE THINGS UP WITH MORE DETAILS (NOT ONLY IN MUSIC... AHEM THIS MESSAGE IS STARTING TO GET LONG AHEM...). ANYWAYS THAT IS THE BACKGROUND OF THIS TUNE. I WANNA THANK DESIRE FOR INVITING ME TO CONTRIBUTE FOR CHIP CHOP 17, THE PEOPLE BEHIND THIS COMPILATION FOR PUTTING IT TOGETHER, AND I WANNA THANK YOU FOR LISTENING! YOU CAN FIND ME ON SOUNDCLOUD, MODARCHIVE.ORG, BANDCAMP, BATTLE OF THE BITS, X (NOT THAT ACTIVE HERE, RIP TWITTER) AND NOW ALSO INSTAGRAM! ON ALL THE PLACES [AT]ASIKWUSPULSE BE SURE TO CHECK OUT THE OTHER ARTISTS ON THIS COMPILATION AS WELL!"
                END_TEXT
Track_AdamJJoyfulContinuation:
                dc.b    "ADAMJ - JOYFUL CONTINUATION           "
                dc.b    "GREETINGS TO REDOX OF MOVSD, POISON, PG, ALL THE ATARI PEOPLE OUT THERE, NOOLY AND RAIST OF MARSHALS, ZDEN OF SATORI, AND ARAGORN OF SQC."
                END_TEXT
Track_WertstahlAlwaysAhead:
                dc.b    "WERTSTAHL - ALWAYS AHEAD!             "
                dc.b    "MADE WITH PROTRACKER 2.6 ON AN AMIGA 500, IF I RECALL CORRECTLY, ""ALWAYS AHEAD"" WAS INSPIRED BY SOME CLASSICAL TUNE. I HOPE I DIDN'T ACTUALLY RIP OFF SOMEONE ELSE'S MELODY FROM THE SCENE. THE NAME IS OF COURSE INSPIRED BY THE FRONT 242 LYRICS OF THEIR SONG NO SHUFFLE. MY TUNE IS ACTUALLY NOTHING SPECIAL EXCEPT MAYBE FOR ITS SIZE OF 12KB WHICH MAKES IT A GOOD CANDIDATE FOR TINY RELEASES. WERTSTAHL OF GP SENDS GREETINGS TO ALL KNOWERS. THANKS TO THE TEAM FOR ADDING MY TUNE TO THIS FINE DSR RELEASE. ALWAYS AHEAD!"
                END_TEXT
Track_SamplrStagnancy:
                dc.b    "SAMPLR - STAGNANCY                    "
                dc.b    "OH, I DON'T KNOW WHAT TO SAY. I ALWAYS LIKED THIS STYLE WHEN MODULE SOUNDS LIKE THE OTHER CONSOLES, AND DID MY OWN STYLE. THANKS TO DESIRE FOR THE OPPORTUNITY TO PARTICIPATE IN THIS MUSIC DISC AND GREETINGS TO ALL PARTICIPANTS (SORRY FOR NOT HAVING NAMES, BUT I THINK YOU ARE GOOD GUYS). MAYBE I SPEAK STRANGELY IN SOME MOMENTS, BUT I THINK IT'S OKAY, I'LL DEVELOP MYSELF. BYE AND GOOD LUCK TO EVERYONE"
                END_TEXT
Track_WOTWHypnotized:
                dc.b    "WOTW - HYPNOTIZED                     "
                dc.b    "IT'S BEEN ALMOST 5 YEARS SINCE I RELEASED MY LAST MODULE WHICH PROOFS HOW FAST TIME IS RUNNING WHEN REACHING A CERTAIN AGE. ANYWAY I AM VERY HAPPY TO BE PART OF CHIP CHOP #17 AND I THINK 'HYPNOTIZE' TURNED OUT REALLY WELL. SOME FAST GREETS TO VIRGILL, IRATA, H2O, SLASH, RAMON, HOFFMANN, JERRY, DASCON, TRIACE, MAKTONE, ALPHA ONE AND ALL THE ARTISTS INVOLVED IN THIS PROJECT. BE PREPARED FOR MORE UPCOMING WORKS THIS YEAR!! YOURS W.O.T.W."    
                END_TEXT
Track_OmniqNexus:
                dc.b    "OMNIQ - NEXUS                         "
                dc.b    "HI! LILA HERE, FROM OMNIQ. I HAVEN'T MADE AN AMIGA MODULE IN YEARS, SO I'M VERY HAPPY TO HAVE AN OPPORTUNITY TO MAKE SOMETHING IN THIS FORMAT AGAIN. I'M CURRENTLY WORKING ON A METAL EP ON MY OTHER ALIAS XTASIS, AND AN ELECTRONIC ALBUM ON OMNIQ. YOU CAN CHECK ME OUT ON BANDCAMP, SPOTIFY, APPLE MUSIC - YOU NAME IT, I'M ON THERE! HOPE YOU PEEPS ENJOY THE REST OF THE COMPILATION! THANKS, LILA"
                END_TEXT
Track_GetafixMovesLikeJagger:
                dc.b    "GETAFIX - MOVES LIKE JAGGER           "
                dc.b    "GETAFIX OF CMAP HERE, SLIDING INTO YOUR EARDRUMS WITH A GROOVE THAT'S GOT MORE SWAG THAN JAGGER HIMSELF—A CHIPTUNE REMAKE THAT'LL MAKE YOUR PIXELS DANCE. ORIGINALLY BY MAROON 5 AND AGUILERA, THIS 2019 CONVERSION HAS BEEN MARINATED AND SEASONED JUST RIGHT FOR THE DESIRE CHIP CHOP 17. NOW, IT'S READY TO BE SERVED HOT AND FRESH, DIRECTLY TO YOUR AUDIO APPETITE. PREPARE YOURSELVES FOR A MUSICAL FEAST THAT PROMISES TO DELIVER ALL THE FUNKY BITS AND BOBS YOU CRAVE. ENJOY THE BEATS, FOLKS!"
                END_TEXT
Track_TNKLockdownLiberation:
                dc.b    "TNK - LOCKDOWN LIBERATION             "
                dc.b    "HI CHIP CHOPPERS AND ALL THE GOOD'OL'MODULES FANS THAT WERE / KNOW / CHERISH THE GOOD OLD 90S "
                dc.b    "AMIGA/PEECEE DEMOSCENE! IT HAS NOW BEEN 30+ YEARS SINCE I WROTE MY LATEST DEMOSTYLE SCROLLER... "
                dc.b    "SO LET'S SEE IF I DIDN'T LOSE MY HABITS AND AM STILL ABLE TO WRITE ONE THAT WILL SCROLL WHILE "
                dc.b    "YOU'LL LISTEN TO MY FIRST CHIPTUNE IN SOMEWHAT 20+ YEARS, A TRACK WRITTEN IN THOSE AWFUL "
                dc.b    "CORONAVIRUS-PANDEMIC YEARS, WHILE WE WERE LOCKED DOWN FOR THE SECOND TIME IN FRANCE, A TIME I "
                dc.b    "LOST MOST OF MY FRIENDS, NOT THROUGH THE PANDEMIC ITSELF, BUT BECAUSE I DARED TO EXPOSE SOME "
                dc.b    "ABSURDITIES OF THE LOCKDOWN RULES, SOMETHING THAT TURNED ME INTO A ""CONSPIRACY THEORICIAN"" TO"
                dc.b    "THEIR EYES, EVEN IF SCIENCE PROVED ME RIGHT ON EVERY POINT SINCE THEN... I HOPE WE'LL NEVER"
                dc.b    "EVER HAVE TO GO THROUGH SUCH A NIGHTMARE, NOR FACE A WORSE ONE, AS THE EUROPEAN NEWS ARE "
                dc.b    "FORECASTING IT... ON A LIGHTER SIDE, LET ME ALSO TELL YOU THAT THE INTRO NOTES OF THAT CHIPTUNE "
                dc.b    "WERE USED IN THE BOOKTRAILER TO MY NOVEL ""LE LIVRE QUI PARLE DE TOI"" (""THE BOOK THAT TELLS "
                dc.b    "ABOUT YOU""), PUBLISHED IN LATE 2022 IN FRANCE (AND IN FRENCH, SORRY...) BY M+ EDITIONS. YEP "
                dc.b    "GUYS, SINCE THE DEMO DAYS, MY LIFE CHANGED QUITE MUCH AND I AM A NOVELIST NOWADAYS (YEP!)... "
                dc.b    "MAYBE ONE DAY ONE OF MY WORKS WILL GET TRANSLATED IN YOUR LANGUAGE TOO! BTW, ONE OF MY UPCOMING "
                dc.b    "NOVEL PROJECT WILL BE SOMEWHAT AUTOBIOGRAPHICAL, AS THE ACTION WILL TAKE PLACE IN THE 90S "
                dc.b    "DEMOSCENE... THE NOVEL WILL BE CALLED ""DEMOMAKER"" (YEP, EVEN IN FRENCH!) AND WELL... LET'S "
                dc.b    "HOPE MY PUBLISHER WILL ACCEPT SUCH AN UNCONVENTIONAL PROJECT! FOR THE REST, GREETINGS TO ALL "
                dc.b    "THE PEOPLE I USED TO KNOW BACK THEN, MY REALTECH/DZONE/CAFFEIN MATES, LIZARDKING, MAF,... AND "
                dc.b    "OF COURSE CORINNE AND MURIEL, THE TWO GIRLS ALL MY MODULES WERE DEDICATED TO BACK THEN... "
                dc.b    "THANKS ALSO TO RAMON DE BRUIJN FOR LETTING ME TAKE PART IN THAT AWESOME PROJECT :-) FOR THE "
                dc.b    "REST, FEEL FREE TO FOLLOW ME ON FACEBOOK AND INSTAGRAM WHERE I AM UNDER MY REAL NAME (PHILIPPE "
                dc.b    "MEISBURGER) AND LET'S KEEP IN TOUCH... I'D FOR SURE STILL HAVE THOUSAND MORE THINGS TO SAY "
                dc.b    "(DIDN'T YOU KNOW NOVELISTS ARE TALKATIVE?), BUT WELL, I GUESS I'M ALREADY BY FAR EXCEEDING MY "
                dc.b    "TEXT QUOTA SO WELL... HAPPY LISTENING TO THIS FUNNY ""LOCKDOWN LIBERATION"", AND LET'S STAY IN "
                dc.b    "TOUCH!"
                END_TEXT
Track_CytronTheMoreThings:
                dc.b    "CYTRON - THE MORE THINGS              "
                dc.b    "ZHAZAM! CYTRON OF DEPTH IS STILL WITH YOU, ALTHOUGH ON LIFE SUPPORT. THIS IS MY FIRST CREATION IN YEARS. IT'S A LOT MORE RUSHED THAN I WOULD HAVE LIKED, BUT IT IS A START. THE REALITY IS I FEEL INFERIOR, NOT SO MUCH TO ALL YOU FELLOW BROTHER AND SISTER SCENERS, BUT TO MY OWN MARVELLOUS MUSICAL PRODIGY DAUGHTER. SHE RECENTLY HAD A 7-MINUTE PIANO TRIO PIECE PERFORMED, LEADING ON THE VIOLIN HERSELF. TALENT, EFFORT, COMMITMENT. HARD TO KEEP UP WITH HER. GREETINGS TO EVERYONE STILL SCENING. I LOVE YOU FOR IT! CYTRONIUS OUT."
                END_TEXT
Track_WeezerMelodieII:
                dc.b    "WEEZER - MELODIE II                   "
                dc.b    "HIYA, THIS IS WEEZER (A.K.A NIMBUS) AT THE KEYBOARD! THIS CHIPTUNE WAS COMPOSED BACK IN THE 90'S, BUT I DON'T REMEMBER THE EXACT YEAR. THE LAST TIME ANY OF MY MODS WERE FEATURED IN A DEMOSCENE PRODUCTION WAS 29 YEARS AGO, SO IT'S AN HONOR TO PARTICIPATE IN THIS EXCELLENT COMPILATION! BIG CHEERS TO DESIRE FOR ASKING ME TO CONTRIBUTE! ENJOY!"
                END_TEXT
Track_ComatronKISS:
                dc.b    "COMATRON - K.I.S.S                    "
                dc.b    "I AM EXTREMELY HAPPY TO BE ON THIS DISK - THANX A LOT GUYS. I WANT TO THANK MY STILL LIVING GRANDMOTHER WHO RAISED ME AND BOUGHT ME AN AMIGA WHEN I WAS 9. THAT LEAD ME TO PRODUCING MUSIC IN THE END. ALSO GREETINGS TO EVERYONE IN THE SCENE - ESPECIALLY DASCON, VIRGIL, MYGG, H0FF, SUPERPLEK, ALKAMA, TEO, EVIL, BONEFISH, AND TRIACE. SPECIAL SHOUT OUT TO MY GOOD FRIEND NOSTAR. I HOPE YOU ENJOY THE LOOP FOR A BIT"
                END_TEXT
Track_RemuteTheCarouselofRemute:
                dc.b    "REMUTE - THE CAROUSEL OF REMUTE       "
                dc.b    "KEEP SPINNIN', LOVE U ALL!"
                END_TEXT
Track_WooberShortReturn:
                dc.b    "WOOBER - SHORT RETURN                 "
                dc.b    "WOOBER HERE, RIDING THE WAVES OF GRATITUDE AND JOY! I WANTED TO DROP YOU A QUICK NOTE TO EXPRESS MY DEEPEST APPRECIATION FOR GIVING ME THE OPPORTUNITY TO COMPOSE A CHIPTUNE FOR CHIP CHOP. CREATING THAT PIECE WAS AN ABSOLUTE BLAST! AFTER BEING AWAY FROM PROTRACKER FOR YEARS, MY RUSTY TRACKING SKILLS CAME SLOWLY ALIVE WHILE POURING MY HEART AND SOUL INTO EVERY BYTE. BIG THANKS TO RAMONSTER AND DSR FOR GIVING ME THIS OPPORTUNITY TO BE PART OF IT. A BIG GREET GOES ALSO OUT TO ALL MY FRIENDS AND DEMOSCENERS."
                END_TEXT
Track_Ne7Banger:
                dc.b    "NE7 - BANGER                          "
                dc.b    "HELLO ME LOVELIES, NE7 AT THE KEYS ERE BASHING AWAY AT A SCROLLIE, BEEN A WHILE SINCE I'VE WRITTEN ONE OF THESE LOL SO WONT DO GREETS AS I'M BOUND TO FORGET SOMEONE. INSTEAD I'LL TALK ABOUT MY DAFT TUNE AND HOW BRAVE IT IS THE TEAM WENT FOR IT AS IT USED THE DREADED EFX PROTRACKER COMMAND OF DOOM TO FECK AROUND WITH THE SAMPLES AS THE TRACK PLAYS :D IF U RIP THIS FROM MEMORY IT'LL BE DIFFERENT EACH TIME U PAUSE THE AR HEHEHE LAUGHS EVILLY FROM THE SOFA ANYWAY HOPE YA LIKE IT AND MY LITTLE ROB TRIBUTE I INSERTED TOO. EVERYONE SHOULD DO AT LEAST ONE ROB TRIBUTE, ITS THE LAW. ANYWAY TIME TO SIGN OFF, AND MAKE SURE YOU MOVE THAT CUP AWAY FROM YOUR AMIGA!"
                END_TEXT
Track_SlazeHypertension:
                dc.b    "SLAZE - HYPERTENSION                  "
                dc.b    "CURRENTLY PLAYING IS 'HYPERTENSION' BY SLAZE, A TRACK CRAFTED FOR CHIPCHOP IN 2021. THE DESIRE TEAM EXTENDS HEARTFELT LOVE AND SUPPORT TO SLAZE AND HIS LOVED ONES THROUGH THESE CHALLENGING TIMES. WE'RE WITH YOU IN SPIRIT, OFFERING OUR SINCEREST CONDOLENCES AND THOUGHTS."
                END_TEXT
Track_TZXTheFleasGotTheCat:
                dc.b    "TZX - THE FLEAS GOT THE CAT           "
                dc.b    "HELLO EVERYONE! TZX AT THE KEYBOARD. I'M VERY GLAD THAT I HAVE THE OPPORTUNITY TO BE PART OF THIS PROJECT. I HOPE YOU HAVE FUN LISTENING TO MY CRAZY TRACK. TO BE HONEST, I'VE NEVER BEEN GOOD AT MAKING CHIP-TUNES, BUT I LOVE LISTENING TO THESE SOUNDS. I'M GLAD I WAS ABLE TO SUPPORT THIS COMPILATION. GREETINGS TO ALL ACTIVE DEMOSCENERS, ESPECIALLY THOSE WHO OPERATE ON DYING PLATFORMS. YOU'RE DOING A GOOD JOB! KISSES FROM POZNAN, BYE!"
                END_TEXT
Track_DannyMattissenTwistedEngine:
                dc.b    "DANNY MATTISSEN - TWISTED ENGINE      "
                dc.b    "DANNY MATTISSEN HERE... I REMEMBER I WAS 21 YEARS OLD WHEN I WROTE THE MUSIC, I HAD MY AMIGA FOR QUITE A WHILE BUT MISSED THE SOUND OF THE COMMODORE 64, AND THEN WROTE THE PIECE IN 1997, HOPE IT BRINGS OUT THE NOSTALGIA IN YOU LISTENERS"
                END_TEXT
Track_GWEMTeaAtMidnight:
                dc.b    "GWEM - TEA AT MIDNIGHT                "
                dc.b    "HELLO, THIS IS GWEM TYPING TO YOU ALL. I HOPE YOU WILL ENJOY MY CONTRIBUTION TO CHIP CHOP! AS YOU CAN HEAR I DECIDED TO TAKE A LITTLE BIT OF A DIFFERENT INTERPRETATION TO ""CHIPTUNE"" THAN IS USUAL, BUT I THINK IT'S GOOD TO PUSH THINGS A BIT. I DON'T HAVE TOO MUCH MORE TO SAY, EXCEPT FOR MY GREETINGS. SHOUT OUT TO MY AMIGA SCENE FRIENDS: MYGG, HOFFMAN, INTERPHACE, GOTO80, C-TRIX, AND POKE-1070! GWEM OUT…"
                END_TEXT
Track_tEISTurminchja:
                dc.b    "NOTORIOUS - MITTEN SMITTEN            "
                dc.b    "HELLO FROM NOTORIOUS, HAPPY TO CONTRIBUTE FOR SUCH A NICE SERIES LIKE CHIP CHOP! I DON'T KNOW ABOUT YOU GUYS BUT I FEEL LIKE TIME IS MOVING FASTER THESE DAYS, IT'S ALREADY EASTER AGAIN. I HOPE YOU ALL FEEL AS I FEEL THAT THE AMIGA IS RISING AGAIN SINCE THE PRODUCTIONS ARE JUST BECOMING BETTER AND BETTER! I HOPE TO SEE YOU AT ANY OF THE UPCOMING PARTIES THIS YEAR! CHEERS TO ALL YOU FRIENDS AND SCENERS OUT THERE."
                END_TEXT
Track_JuiceSpaceJam:
                dc.b    "JUICE - SPACE JAM                     "
                dc.b    "HEYA REVISIONEERS, FRIENDS OF THE DEMOSCENE AND CHIPTUNE LOVERS! JUICE ON THE KEYS TYPING SOME WORDS ABOUT THE TUNE CURRENTLY ASSAULTING YOUR EARDRUMS. FIRST OF ALL, I HAVE TO SAY THAT I'M VERY HAPPY AND HONORED TO BE A PART OF THIS MONSTER RELEASE. IT'S AN HONOR TO BE IN THE GOOD COMPANY SOME OF THE FINEST CHIPTUNE MUSICIANS AROUND! I'VE BEEN INACTIVE IN THE SCENE FOR A WHILE NOW, OVERWHELMED WITH REAL LIFE AND CONTENT TO JUST WATCH FROM THE SIDELINES, BUT THAT IS ABOUT TO CHANGE IN 2024. I PLAN TO MAKE AT LEAST ONE NEW TUNE EVERY MONTH THIS YEAR. THE ONE YOU'RE LISTENING TO RIGHT NOW IS 03/12. THE FIRST TWO ARE IN THE BAG, MEANT FOR A COUPLE OF DIFFERENT PRODS WHICH ARE STILL UNRELEASED AT THE TIME OF WRITING. IF ALL GOES ACCORDING TO PLAN, YOU MIGHT HEAR ALL THREE THIS EASTER AT REVISION! UNFORTUNATELY, I WON'T BE ABLE TO ATTEND THIS YEAR, BUT I'M THERE WITH YOU ALL IN SPIRIT! A BIG SHOUT OUT TO ALL MY FELLOW MEMBERS OF REALITY AND INSANE, ALL THE CREW AND MUSICIANS BEHIND CHIPCHOP, ALL MY OTHER FRIENDS I'VE MADE OVER THE YEARS IN THE SCENE, EVERYBODY ATTENDING REVISION THIS EASTER... AND YOU! :)"
                END_TEXT
Track_Goto80Jeffrix:
                dc.b    "GOTO80 - JEFFRIX                      "
                dc.b    "ALOHA, AMIGA SAILORS! HOPE YOU'RE FEELING UP FOR SOME FONKY PLAYTIME.. I KNOW THIS ISN'T EXACTLY KOSHER AMIGA CHIP .. HEHEHE .. BUT I'M SURE YOUR GRANDCHILDREN WILL LIKE IT THE SONG STARTED AS A REMIX OF JEFF'S C64-SONG HARD-TRACK BUT YOU WON'T RECOGNIZE MUCH FROM IT ANYMORE ANYWAY, ENJOY RESPONSIBLY! .."
                END_TEXT
Track_MisterRobotoLickMyBalls:
                dc.b    "MISTER ROBOTO - LICKMYBALLS           "
                dc.b    "WHAT THE ACTUAL FUCK? THIS DOES NOT SOUND AS IF IT SHOULD BE CALLED A CHIP MUSIC MODULE!! WELL, I SUPPOSE IF THIS CAUSES OFFENSE TO YOUR PRECIOUS SENSIBILITIES THEN YOU CAN DO AS THE WORDS IN THIS SONG SAY THAT YOU CAN DO. I DID A TRICK WITH THE SOUND DATA WHERE I WAS ABLE TO USE THREE MORE SOUNDS THAN THE FORMAT MIGHT TYPICALLY ALLOW."
                END_TEXT
Track_MisterRobotoOutOfMyHouse:
                dc.b    "MISTER ROBOTO - OUT OF MY HOUSE       "
                dc.b    "WAIT, ER... THERE ARE WORDS IN MY CHIP TUNE! TAKE THIS ONE BACK AND BRING ANOTHER ONE NOW. WELL ANYWAY THANKS TO CTRIX FOR ALL THE DRUM SAMPLES AND ALSO URBAN SHAKEDOWN FOR MOST ALL THE SYNTH SAMPLES. AND ALSO STEPHEN HAWKING'S GHOST WHO SANG ALL THE LYRICS FOR THIS LITTLE SONG THAT WAS INSPIRED BY THE CLASSIC SONG BY RUN DMC. SAY NO TO DRUGS. STAY OLD SCHOOL AND GET OUT OF MY HAUS BITCH!"
                END_TEXT
Track_AkaobiRestlessBlipper:
                dc.b    "AKAOBI - RESTLESS BLIPPER             "
                dc.b    "BLIP BLOP HI, I'M AKAOBI FROM TOKYO. HAVING OWED TO THE DEMOSCENE AND TRACKED MUSIC FOR A LONG TIME, FINALLY THIS IS MY VERY FIRST AMIGA MODULE. GREETZ TO CHIP ENTHUSIASTS AND 8-BIT SAMPLE WIZARDS AROUND THE WORLD."
                END_TEXT
Track_NOXW20M40M80P:
                dc.b    "NOXW - 20M40M80P                      "
                dc.b    "20M40M80P. SUBTERFUGED & UTILITARIAN. NU DIMENSIONZ IN NO1Z.I AM A FAIRLY UNKNOWN FORCE THAT COMES FROM MIDDLE EUROPE. I MAKE WEIRD MUSIC FOR WEIRD PPL. UNAPOLOGETICALLY S1CK. IF UR WILLING TO SIGN ME UP TO A DEMOGROUP OR ANY OTHER PROJECTS, CONTACT ME. OLOLOVITEK1@YANDEX.COM. I HAVE TOO MUCH TIME IN MY HANDS. SPECIAL THX TO DSR, THE LOBIT SCENE & MODERN NETLABELS LIKE FNL, FCC & FLEA MARKET."
                END_TEXT
